Adding Server Model Unit  Tests
phoenixnap/pnapctl pull request #41
Opened 2021-12-06 15:49 UTC by brian-zammit

2021-12-14 10:45 UTC, brian-zammit commented on src/common/models/bmcapimodels/servermodels/testutil_servergenerator.go
> +func GenerateClusterListSdk(n int) []ranchersdk.Cluster {
Removed the Cluster Generation methods from this server generator. Thanks

2021-12-15 11:39 UTC, andrewbu-ccbill requested changes

2021-12-15 11:39 UTC, andrewbu-ccbill commented on src/common/models/bmcapimodels/servermodels/serverreserve_test.go
> +func TestServerReserveToSDK(test_framework *testing.T) {
```suggestion
func TestServerReserveToSdk(test_framework *testing.T) {
```

2021-12-15 11:39 UTC, andrewbu-ccbill commented on src/common/models/bmcapimodels/servermodels/serverpach_test.go
> +func TestServerPatchToSDK(test_framework *testing.T) {
```suggestion
func TestServerPatchToSdk(test_framework *testing.T) {
```

2021-12-15 11:42 UTC, andrewbu-ccbill approved these changes

2021-12-15 11:57 UTC, brian-zammit reviewed
Looks good to me ✔️

2021-12-15 11:58 UTC, merged